"use client";

import { useActionState, useMemo, useState } from "react";
import type { DataReadinessActionState } from "@/app/admin/data-readiness/actions";

type Row=Record<string,unknown>;
type Action=(state:DataReadinessActionState,form:FormData)=>Promise<DataReadinessActionState>;
type Props={contacts:Row[];events:Row[];leads:Row[];services:Row[];batches:Row[];items:Row[];activity:Row[];warning:string|null;manageContactAction:Action;manageEventAction:Action;manageLeadAction:Action;stageManifestAction:Action;approveBatchAction:Action;applyBatchAction:Action;compensateBatchAction:Action};
const INITIAL:DataReadinessActionState={status:"idle",message:""};
const text=(row:Row,key:string)=>typeof row[key]==="string"?String(row[key]):"";
const short=(value:unknown)=>String(value??"").slice(0,12);
const dateTimeInput=(value:unknown,timeZone:string)=>{if(!value)return "";const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(String(value)));const part=(type:string)=>parts.find(candidate=>candidate.type===type)?.value??"";return `${part("year")}-${part("month")}-${part("day")}T${part("hour")}:${part("minute")}`;};

function Feedback({state}:{state:DataReadinessActionState}){return state.message?<div className={`operational-message ${state.status}`} role={state.status==="error"?"alert":"status"}><b>{state.message}</b>{state.errors?.length?<ul>{state.errors.map((error)=><li key={error}>{error}</li>)}</ul>:null}</div>:null;}

function ContactEditor({contact,action}:{contact?:Row;action:Action}){
  const [state,formAction,pending]=useActionState(action,INITIAL); const existing=Boolean(contact);
  return <form action={formAction} className="data-form"><input name="contact_id" type="hidden" value={text(contact??{},"id")}/>
    <div className="data-form-grid"><label><span>Display name</span><input defaultValue={text(contact??{},"display_name")} maxLength={160} name="display_name" required/></label><label><span>Email</span><input defaultValue={text(contact??{},"primary_email")} maxLength={254} name="primary_email" type="email"/></label><label><span>Phone</span><input defaultValue={text(contact??{},"primary_phone")} maxLength={40} name="primary_phone" type="tel"/></label><label><span>Organization</span><input defaultValue={text(contact??{},"organization_name")} maxLength={160} name="organization_name"/></label><label><span>First name</span><input defaultValue={text(contact??{},"first_name")} maxLength={100} name="first_name"/></label><label><span>Last name</span><input defaultValue={text(contact??{},"last_name")} maxLength={100} name="last_name"/></label><label><span>Preferred channel</span><select defaultValue={text(contact??{},"preferred_channel")||"email"} name="preferred_channel"><option value="email">Email</option><option value="text">Text</option><option value="phone">Phone</option><option value="portal">Portal</option></select></label><label className="span"><span>Owner notes</span><textarea defaultValue={text(contact??{},"notes")} maxLength={2000} name="notes" rows={2}/></label></div>
    <div className="data-actions"><button className="primary-button" disabled={pending} name="action" value={existing?"update":"create"} type="submit">{pending?"Saving…":existing?"Save contact":"Create contact"}</button>{existing?<><button className="secondary-button" formNoValidate name="action" value={text(contact??{},"status")==="archived"?"restore":"archive"} type="submit">{text(contact??{},"status")==="archived"?"Restore":"Archive"}</button><span className="status-pill">{text(contact??{},"status")}</span></>:null}</div><Feedback state={state}/></form>;
}

function EventEditor({event,services,action}:{event:Row;services:Row[];action:Action}){
  const [state,formAction,pending]=useActionState(action,INITIAL); const timezone=text(event,"timezone")||"America/Indiana/Indianapolis";
  return <form action={formAction} className="data-form"><input name="event_id" type="hidden" value={text(event,"id")}/><input name="action" type="hidden" value="update"/><div className="data-form-grid"><label><span>Event title</span><input defaultValue={text(event,"title")} maxLength={180} name="title" required/></label><label><span>Event type</span><input defaultValue={text(event,"event_type")} maxLength={80} name="event_type" required/></label><label><span>Status</span><select defaultValue={text(event,"status")} name="status">{["draft","inquiry","quoted","pending","booked","planning","ready","active","completed","cancelled","archived"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Timezone</span><input defaultValue={timezone} maxLength={100} name="timezone"/></label><label><span>Starts</span><input defaultValue={dateTimeInput(event.starts_at,timezone)} name="starts_at" type="datetime-local"/></label><label><span>Ends</span><input defaultValue={dateTimeInput(event.ends_at,timezone)} name="ends_at" type="datetime-local"/></label><label><span>Venue</span><input defaultValue={text(event,"venue_name")} maxLength={180} name="venue_name"/></label><label><span>Address</span><input defaultValue={text(event,"venue_address_1")} maxLength={200} name="venue_address_1"/></label><label><span>Address line 2</span><input defaultValue={text(event,"venue_address_2")} maxLength={160} name="venue_address_2"/></label><label><span>City</span><input defaultValue={text(event,"venue_city")} maxLength={120} name="venue_city"/></label><label><span>State</span><input defaultValue={text(event,"venue_state")} maxLength={80} name="venue_state"/></label><label><span>Postal code</span><input defaultValue={text(event,"venue_postal_code")} maxLength={24} name="venue_postal_code"/></label><label><span>Guest count</span><input defaultValue={String(event.guest_count??"")} min={0} name="guest_count" type="number"/></label><fieldset className="span"><legend>Booked services</legend><label className="data-service-toggle"><input name="replace_services" type="checkbox" value="true"/>Replace this booking’s service selection</label><div className="data-checks">{services.map(service=><label key={text(service,"id")}><input name="service_ids" type="checkbox" value={text(service,"id")}/>{text(service,"name")}</label>)}</div><small>Leave replacement off to preserve every current booked service. Turn it on only after reviewing the full selection.</small></fieldset></div><div className="data-actions"><button className="primary-button" disabled={pending}>Save event</button><button className="secondary-button" formAction={formAction} formNoValidate name="action" value={text(event,"status")==="archived"?"restore":"archive"} type="submit">{text(event,"status")==="archived"?"Restore":"Archive"}</button></div><Feedback state={state}/></form>;
}

function LeadEditor({lead,action}:{lead:Row;action:Action}){
  const [state,formAction,pending]=useActionState(action,INITIAL); return <form action={formAction} className="data-inline-form"><input name="lead_id" type="hidden" value={text(lead,"id")}/><input name="action" type="hidden" value="update"/><label><span>Status</span><select defaultValue={text(lead,"status")} name="status">{["new","qualifying","quoted","follow_up","won","lost","archived"].map(v=><option key={v}>{v.replace("_"," ")}</option>)}</select></label><label><span>Next follow-up</span><input defaultValue={text(lead,"next_follow_up_at").slice(0,10)} name="next_follow_up_at" type="date"/></label><button className="primary-button" disabled={pending}>Save</button><button className="secondary-button" formAction={formAction} formNoValidate name="action" value={text(lead,"status")==="archived"?"restore":"archive"} type="submit">{text(lead,"status")==="archived"?"Restore":"Archive"}</button><Feedback state={state}/></form>;
}

function BatchCard({batch,items,approve,apply,compensate}:{batch:Row;items:Row[];approve:Action;apply:Action;compensate:Action}){
  const [approveState,approveAction]=useActionState(approve,INITIAL); const [applyState,applyAction]=useActionState(apply,INITIAL); const [rollbackState,rollbackAction]=useActionState(compensate,INITIAL); const hash=text(batch,"manifest_hash");
  const reviewable=items.filter(item=>["previewed","approved","failed","excluded"].includes(text(item,"status")));
  const hasApproved=items.some(item=>text(item,"status")==="approved"); const hasApplied=items.some(item=>text(item,"status")==="applied");
  return <article className="data-batch"><header><div><span className="eyebrow">{text(batch,"source_label")}</span><h3>{short(hash)}…</h3></div><span className="status-pill">{text(batch,"status")}</span></header><p>{items.length} reviewed item{items.length===1?"":"s"} · {Number(batch.created_count??0)} applied · {Number(batch.error_count??0)} failed</p><form action={approveAction}><input name="batch_id" type="hidden" value={text(batch,"id")}/><input name="manifest_hash" type="hidden" value={hash}/><div className="data-item-list">{items.map(item=>{const canReview=reviewable.includes(item);return <label className="data-item" key={text(item,"id")}>{canReview?<input defaultChecked={text(item,"status")!=="excluded"} name="item_keys" type="checkbox" value={text(item,"item_key")}/>:<span aria-hidden="true" className="data-item-done">✓</span>}<span><b>{text(item,"candidate_type").replaceAll("_"," ")}</b><small>{text(item,"item_key")} · {text(item,"status")}{Array.isArray(item.duplicate_warnings)&&item.duplicate_warnings.length?` · ${item.duplicate_warnings.length} duplicate warning(s)`:""}</small></span></label>})}</div>{reviewable.length?<button className="secondary-button" type="submit">Approve exact item set</button>:null}</form>{hasApproved?<form action={applyAction} className="data-actions"><input name="batch_id" type="hidden" value={text(batch,"id")}/><input name="manifest_hash" type="hidden" value={hash}/><button className="primary-button" type="submit">Apply approved items</button></form>:null}{hasApplied?<details className="danger-zone"><summary>Archive / compensate this batch</summary><form action={rollbackAction}><input name="batch_id" type="hidden" value={text(batch,"id")}/><input name="manifest_hash" type="hidden" value={hash}/><label><span>Type ARCHIVE BATCH</span><input name="confirmation" autoComplete="off"/></label><button className="danger-button" type="submit">Archive imported results</button></form></details>:null}<Feedback state={approveState.status!=="idle"?approveState:applyState.status!=="idle"?applyState:rollbackState}/></article>;
}

export function DataReadinessWorkspace(props:Props){
  const [section,setSection]=useState<"records"|"intake"|"history">("records"); const [manifestState,manifestAction,pending]=useActionState(props.stageManifestAction,INITIAL);
  const itemsByBatch=useMemo(()=>new Map(props.batches.map(batch=>[text(batch,"id"),props.items.filter(item=>text(item,"batch_id")===text(batch,"id"))])),[props.batches,props.items]);
  return <main className="admin-main data-readiness-main"><header className="admin-header compact"><div><span className="eyebrow">Owner tools</span><h1>Data Readiness</h1><p>Correct canonical records and approve exact, traceable intake batches. Nothing merges or deletes automatically.</p></div></header>{props.warning?<div className="alert warning">Some data could not be loaded. No write controls should be used until the page is complete.</div>:null}<nav className="data-tabs" aria-label="Data readiness sections">{[["records","Records"],["intake","Reviewed intake"],["history","History"]].map(([id,label])=><button aria-current={section===id?"page":undefined} className={section===id?"active":""} key={id} onClick={()=>setSection(id as typeof section)}>{label}</button>)}</nav>
    {section==="records"?<div className="data-stack"><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Contacts</span><h2>Create and correct contacts</h2></div><span className="status-dot">{props.contacts.length}</span></header><details open><summary>Create contact</summary><ContactEditor action={props.manageContactAction}/></details>{props.contacts.map(contact=><details key={text(contact,"id")}><summary>{text(contact,"display_name")||"Unnamed contact"} <small>{text(contact,"status")}</small></summary><ContactEditor action={props.manageContactAction} contact={contact}/></details>)}</section><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Events</span><h2>Correct canonical gigs and inquiries</h2></div><span className="status-dot">{props.events.length}</span></header>{props.events.map(event=><details key={text(event,"id")}><summary>{text(event,"title")} <small>{text(event,"status")}</small></summary><EventEditor action={props.manageEventAction} event={event} services={props.services}/></details>)}</section><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Leads</span><h2>Status and follow-up</h2></div><span className="status-dot">{props.leads.length}</span></header>{props.leads.map(lead=><article className="data-lead" key={text(lead,"id")}><b>Lead {short(lead.id)}</b><LeadEditor action={props.manageLeadAction} lead={lead}/></article>)}</section></div>:null}
    {section==="intake"?<div className="data-stack"><section className="panel"><span className="eyebrow">Dry run</span><h2>Stage intake_manifest_v1</h2><p className="panel-note">Paste a reviewed manifest only—not source emails, PDFs, screenshots, or credentials. Validation completes before staging writes occur.</p><form action={manifestAction}><label><span>Versioned JSON manifest</span><textarea className="manifest-input" maxLength={524288} name="manifest" required rows={12} spellCheck={false}/></label><button className="primary-button" disabled={pending}>{pending?"Validating…":"Validate and stage dry run"}</button></form><Feedback state={manifestState}/></section><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Exact approval</span><h2>Staged batches</h2></div><span className="status-dot">{props.batches.length}</span></header>{props.batches.length?props.batches.map(batch=><BatchCard apply={props.applyBatchAction} approve={props.approveBatchAction} batch={batch} compensate={props.compensateBatchAction} items={itemsByBatch.get(text(batch,"id"))??[]} key={text(batch,"id")}/>):<p className="empty-state compact">No reviewed data-readiness batches.</p>}</section></div>:null}
    {section==="history"?<section className="panel"><header className="panel-heading"><div><span className="eyebrow">Provenance</span><h2>Data Readiness activity</h2></div><span className="status-dot">{props.activity.length}</span></header><div className="data-history">{props.activity.length?props.activity.map(row=><article key={text(row,"id")}><b>{text(row,"event_type").replace("data_readiness.","").replaceAll("_"," ")}</b><span>{new Date(text(row,"occurred_at")).toLocaleString()}</span><small>Event {short(row.event_id)||"—"} · Contact {short(row.contact_id)||"—"}</small></article>):<p>No Data Readiness changes have been recorded.</p>}</div></section>:null}
  </main>;
}
