"use client";

import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import type { DataReadinessActionState } from "@/app/admin/data-readiness/actions";
import { BatchCard } from "@/components/data-readiness-workspace";

type Row=Record<string,unknown>;
type Action=(state:DataReadinessActionState,form:FormData)=>Promise<DataReadinessActionState>;
type Props={contacts:Row[];events:Row[];leads:Row[];services:Row[];batches:Row[];items:Row[];activity:Row[];cleanupBatches:Row[];cleanupItems:Row[];cleanupEnabled:boolean;warning:string|null;manageContactAction:Action;manageEventAction:Action;manageLeadAction:Action;stageManifestAction:Action;approveBatchAction:Action;applyBatchAction:Action;compensateBatchAction:Action;previewCleanupAction:Action;archiveCleanupCustomersAction:Action;restoreCleanupCustomersAction:Action;quarantineCleanupOutboxAction:Action;restoreCleanupOutboxAction:Action};
const INITIAL:DataReadinessActionState={status:"idle",message:""};
const text=(row:Row|undefined,key:string)=>typeof row?.[key]==="string"?String(row[key]):"";
const short=(value:unknown)=>String(value??"").slice(0,12);
const dateInput=(value:unknown)=>value?new Date(String(value)).toISOString().slice(0,10):"";
const dateTimeInput=(value:unknown)=>value?new Date(String(value)).toISOString().slice(0,16):"";

function Feedback({state}:{state:DataReadinessActionState}){return state.message?<div className={`operational-message ${state.status}`} role={state.status==="error"?"alert":"status"}><b>{state.message}</b>{state.errors?.length?<ul>{state.errors.map(error=><li key={error}>{error}</li>)}</ul>:null}</div>:null;}

function ContactEditor({row,action}:{row?:Row;action:Action}){const [state,formAction,pending]=useActionState(action,INITIAL);const archived=text(row,"status")==="archived";return <form action={formAction} className="data-form"><input name="contact_id" type="hidden" value={text(row,"id")}/><div className="data-form-grid"><label><span>Display name</span><input defaultValue={text(row,"display_name")} maxLength={160} name="display_name" required/></label><label><span>Email</span><input defaultValue={text(row,"primary_email")} maxLength={254} name="primary_email" type="email"/></label><label><span>Phone</span><input defaultValue={text(row,"primary_phone")} maxLength={40} name="primary_phone" type="tel"/></label><label><span>Organization</span><input defaultValue={text(row,"organization_name")} maxLength={160} name="organization_name"/></label><label><span>First name</span><input defaultValue={text(row,"first_name")} maxLength={100} name="first_name"/></label><label><span>Last name</span><input defaultValue={text(row,"last_name")} maxLength={100} name="last_name"/></label><label><span>Preferred channel</span><select defaultValue={text(row,"preferred_channel")||"email"} name="preferred_channel"><option value="email">Email</option><option value="text">Text</option><option value="phone">Phone</option><option value="portal">Portal</option></select></label><label className="span"><span>Owner notes</span><textarea defaultValue={text(row,"notes")} maxLength={2000} name="notes" rows={3}/></label></div><div className="data-actions"><button className="primary-button" disabled={pending} name="action" value={row?"update":"create"}>{pending?"Saving…":row?"Save contact":"Create contact"}</button>{row?<button className="secondary-button" formNoValidate name="action" onClick={event=>{if(!archived&&!confirm("Archive this contact? History remains available."))event.preventDefault();}} value={archived?"restore":"archive"}>{archived?"Restore":"Archive"}</button>:null}</div><Feedback state={state}/></form>}

function EventEditor({row,services,action}:{row:Row;services:Row[];action:Action}){const [state,formAction,pending]=useActionState(action,INITIAL);const archived=text(row,"status")==="archived";return <form action={formAction} className="data-form"><input name="event_id" type="hidden" value={text(row,"id")}/><div className="data-form-grid"><label><span>Title</span><input defaultValue={text(row,"title")} maxLength={180} name="title" required/></label><label><span>Event type</span><input defaultValue={text(row,"event_type")} maxLength={80} name="event_type" required/></label><label><span>Status</span><select defaultValue={text(row,"status")} name="status">{["draft","inquiry","quoted","pending","booked","planning","ready","active","completed","cancelled","archived"].map(value=><option key={value}>{value}</option>)}</select></label><label><span>Timezone</span><input defaultValue={text(row,"timezone")||"America/Indiana/Indianapolis"} name="timezone"/></label><label><span>Starts</span><input defaultValue={dateTimeInput(row.starts_at)} name="starts_at" type="datetime-local"/></label><label><span>Ends</span><input defaultValue={dateTimeInput(row.ends_at)} name="ends_at" type="datetime-local"/></label><label><span>Venue</span><input defaultValue={text(row,"venue_name")} name="venue_name"/></label><label><span>Address</span><input defaultValue={text(row,"venue_address_1")} name="venue_address_1"/></label><label><span>Address line 2</span><input defaultValue={text(row,"venue_address_2")} name="venue_address_2"/></label><label><span>City</span><input defaultValue={text(row,"venue_city")} name="venue_city"/></label><label><span>State</span><input defaultValue={text(row,"venue_state")} name="venue_state"/></label><label><span>Postal code</span><input defaultValue={text(row,"venue_postal_code")} name="venue_postal_code"/></label><label><span>Guest count</span><input defaultValue={String(row.guest_count??"")} min={0} name="guest_count" type="number"/></label><fieldset className="span"><legend>Booked services</legend><label className="data-service-toggle"><input name="replace_services" type="checkbox" value="true"/>Replace the current booking selection</label><div className="data-checks">{services.map(service=><label key={text(service,"id")}><input name="service_ids" type="checkbox" value={text(service,"id")}/>{text(service,"name")}</label>)}</div></fieldset></div><div className="data-actions"><button className="primary-button" disabled={pending} name="action" value="update">Save gig</button><button className="secondary-button" formNoValidate name="action" onClick={event=>{if(!archived&&!confirm("Archive this gig? Related history remains available."))event.preventDefault();}} value={archived?"restore":"archive"}>{archived?"Restore":"Archive"}</button></div><Feedback state={state}/></form>}

function LeadEditor({row,action}:{row:Row;action:Action}){const [state,formAction,pending]=useActionState(action,INITIAL);const archived=text(row,"status")==="archived";return <form action={formAction} className="data-form"><input name="lead_id" type="hidden" value={text(row,"id")}/><div className="data-form-grid"><label><span>Status</span><select defaultValue={text(row,"status")} name="status">{["new","qualifying","quoted","follow_up","won","lost","archived"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label><span>Next follow-up</span><input defaultValue={dateInput(row.next_follow_up_at)} name="next_follow_up_at" type="date"/></label></div><div className="data-actions"><button className="primary-button" disabled={pending} name="action" value="update">Save lead</button><button className="secondary-button" formNoValidate name="action" onClick={event=>{if(!archived&&!confirm("Archive this lead? History remains available."))event.preventDefault();}} value={archived?"restore":"archive"}>{archived?"Restore":"Archive"}</button></div><Feedback state={state}/></form>}

function CleanupCard({batch,archiveCustomers,restoreCustomers,quarantineOutbox,restoreOutbox}:{batch:Row;archiveCustomers:Action;restoreCustomers:Action;quarantineOutbox:Action;restoreOutbox:Action}){const customerRestore=text(batch,"customer_status")==="archived",outboxRestore=text(batch,"outbox_status")==="quarantined";const [customerState,customerAction]=useActionState(customerRestore?restoreCustomers:archiveCustomers,INITIAL);const [outboxState,outboxAction]=useActionState(outboxRestore?restoreOutbox:quarantineOutbox,INITIAL);return <article className="data-batch cleanup-batch"><header><div><span className="eyebrow">Owner-reviewed cleanup</span><h3>Verified cleanup scope</h3></div><span className="status-pill">{text(batch,"customer_status")} / {text(batch,"outbox_status")}</span></header><div className="cleanup-counts"><span><b>{Number(batch.contact_count)+Number(batch.lead_count)+Number(batch.event_count)}</b> customer records</span><span><b>{Number(batch.integration_outbox_count)+Number(batch.automation_outbox_count)}</b> outbox items</span></div><div className="cleanup-actions"><form action={customerAction}><input name="batch_id" type="hidden" value={text(batch,"id")}/><input name="manifest_hash" type="hidden" value={text(batch,"manifest_hash")}/><label><span>{customerRestore?"Type RESTORE CUSTOMER BATCH":"Type ARCHIVE 17 CONTACTS, 25 LEADS, 26 EVENTS"}</span><input autoComplete="off" name="confirmation"/></label><button className={customerRestore?"secondary-button":"danger-button"}>{customerRestore?"Restore customer batch":"Archive exact customer batch"}</button><Feedback state={customerState}/></form><form action={outboxAction}><input name="batch_id" type="hidden" value={text(batch,"id")}/><input name="manifest_hash" type="hidden" value={text(batch,"manifest_hash")}/><label><span>{outboxRestore?"Type RESTORE OUTBOX BATCH":"Type QUARANTINE 57 OUTBOX ITEMS"}</span><input autoComplete="off" name="confirmation"/></label><button className={outboxRestore?"secondary-button":"danger-button"}>{outboxRestore?"Restore outbox batch":"Quarantine exact outbox batch"}</button><Feedback state={outboxState}/></form></div></article>}

export function RecordsIntakeWorkspace(props:Props){
  const [section,setSection]=useState<"records"|"intake"|"history">("records"),[kind,setKind]=useState<"contacts"|"events"|"leads"|"archived">("contacts"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[sort,setSort]=useState("updated"),[page,setPage]=useState(0),[editor,setEditor]=useState<{type:"contact"|"event"|"lead"|"new";row?:Row}|null>(null);
  const editorRef=useRef<HTMLElement>(null),priorFocus=useRef<HTMLElement|null>(null);
  const [manifestState,manifestAction,manifestPending]=useActionState(props.stageManifestAction,INITIAL),[cleanupState,cleanupAction,cleanupPending]=useActionState(props.previewCleanupAction,INITIAL);
  const batchItems=useMemo(()=>new Map(props.batches.map(batch=>[text(batch,"id"),props.items.filter(item=>text(item,"batch_id")===text(batch,"id"))])),[props.batches,props.items]);
  const rows=useMemo(()=>{const all=[...props.contacts.map(row=>({...row,_type:"contact"})),...props.events.map(row=>({...row,_type:"event"})),...props.leads.map(row=>({...row,_type:"lead"}))];const base=kind==="archived"?all.filter(row=>text(row,"status")==="archived"):all.filter(row=>text(row,"_type")===kind.slice(0,-1)&&text(row,"status")!=="archived");const q=query.toLowerCase();return base.filter(row=>(status==="all"||text(row,"status")===status)&&(!q||["display_name","organization_name","title","event_type","source","status"].some(key=>text(row,key).toLowerCase().includes(q)))).sort((a,b)=>sort==="name"?(text(a,"display_name")||text(a,"title")).localeCompare(text(b,"display_name")||text(b,"title")):text(b,"updated_at").localeCompare(text(a,"updated_at")));},[props.contacts,props.events,props.leads,kind,query,status,sort]);
  const pages=Math.max(1,Math.ceil(rows.length/10)),safePage=Math.min(page,pages-1),pageRows=rows.slice(safePage*10,safePage*10+10);
  const showEditor=(next:{type:"contact"|"event"|"lead"|"new";row?:Row})=>{priorFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setEditor(next);};
  const closeEditor=()=>{setEditor(null);priorFocus.current?.focus();};
  const open=(row:Row)=>showEditor({type:text(row,"_type") as "contact"|"event"|"lead",row});
  const editorRow=editor?.type==="contact"?props.contacts.find(row=>text(row,"id")===text(editor.row,"id")):editor?.type==="event"?props.events.find(row=>text(row,"id")===text(editor.row,"id")):editor?.type==="lead"?props.leads.find(row=>text(row,"id")===text(editor.row,"id")):undefined;
  useEffect(()=>{if(!editor)return;editorRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")closeEditor();};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[editor]);
  return <main className="admin-main data-readiness-main"><header className="admin-header compact records-header"><div><span className="eyebrow">Owner workspace</span><h1>Records &amp; Intake</h1><p>Find and correct records, review controlled intake, and preserve searchable history.</p></div>{section==="records"?<button className="primary-button" onClick={()=>showEditor({type:"new"})}>Create contact</button>:null}</header>{props.warning?<div className="alert warning" role="alert">{props.warning}</div>:null}<nav className="data-tabs" aria-label="Records and intake sections">{[["records","Records"],["intake","Reviewed Intake"],["history","History"]].map(([id,label])=><button aria-current={section===id?"page":undefined} className={section===id?"active":""} key={id} onClick={()=>setSection(id as typeof section)}>{label}</button>)}</nav>
  {section==="records"?<><nav className="record-type-tabs" aria-label="Record type">{[["contacts","Contacts"],["events","Gigs"],["leads","Leads"],["archived","Archived"]].map(([id,label])=><button className={kind===id?"active":""} key={id} onClick={()=>{setKind(id as typeof kind);setPage(0);}}>{label}</button>)}</nav><section className="panel records-panel"><div className="records-toolbar"><label className="record-search"><span className="sr-only">Search records</span><input onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Search names, titles, source…" type="search" value={query}/></label><label><span className="sr-only">Status</span><select onChange={event=>{setStatus(event.target.value);setPage(0);}} value={status}><option value="all">All statuses</option>{["active","inactive","new","qualifying","quoted","follow_up","won","lost","draft","inquiry","pending","booked","planning","ready","completed","cancelled","archived"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label><span className="sr-only">Sort</span><select onChange={event=>setSort(event.target.value)} value={sort}><option value="updated">Recently updated</option><option value="name">Name / title</option></select></label></div><div className="records-list">{pageRows.length?pageRows.map(row=><button className="record-row" key={`${text(row,"_type")}-${text(row,"id")}`} onClick={()=>open(row)}><span className="record-kind">{text(row,"_type")}</span><b>{text(row,"display_name")||text(row,"title")||`${text(row,"source")||"Lead"} inquiry`}</b><span>{text(row,"event_type")||text(row,"source")||"HQ record"}</span><span className="status-pill">{text(row,"status")}</span><span aria-hidden="true">›</span></button>):<p className="empty-state compact">No records match these filters.</p>}</div><footer className="records-pagination"><span>{rows.length?`${page*10+1}–${Math.min(rows.length,page*10+10)} of ${rows.length}`:"0 records"}</span><div><button disabled={page===0} onClick={()=>setPage(value=>Math.max(0,value-1))}>Previous</button><button disabled={page>=pages-1} onClick={()=>setPage(value=>Math.min(pages-1,value+1))}>Next</button></div></footer></section></>:null}
  {section==="intake"?<div className="data-stack compact-stack"><section className="panel"><details><summary><span><b>Stage reviewed intake</b><small> — validate before any canonical write</small></span></summary><form action={manifestAction} className="compact-manifest"><label><span>Versioned JSON manifest</span><textarea className="manifest-input" maxLength={524288} name="manifest" required rows={8} spellCheck={false}/></label><button className="primary-button" disabled={manifestPending}>{manifestPending?"Validating…":"Validate and stage dry run"}</button><Feedback state={manifestState}/></form></details></section><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Reviewed batches</span><h2>Intake queue</h2></div><span className="status-dot">{props.batches.length}</span></header>{props.batches.length?props.batches.map(batch=><BatchCard apply={props.applyBatchAction} approve={props.approveBatchAction} batch={batch} compensate={props.compensateBatchAction} items={batchItems.get(text(batch,"id"))??[]} key={text(batch,"id")}/>):<p className="empty-state compact">No reviewed intake batches.</p>}</section></div>:null}
  {section==="history"?<div className="data-stack compact-stack"><section className="panel">{props.cleanupEnabled?<><details open><summary><span><b>Bounded Owner cleanup</b><small> — exact reviewed artifact only</small></span></summary><form action={cleanupAction} className="compact-manifest"><label><span>Choose the exact private cleanup manifest</span><input accept="application/json,.json" name="cleanup_manifest" required type="file"/></label><button className="secondary-button" disabled={cleanupPending}>{cleanupPending?"Verifying…":"Verify cleanup preview"}</button><Feedback state={cleanupState}/></form></details>{props.cleanupBatches.map(batch=><CleanupCard archiveCustomers={props.archiveCleanupCustomersAction} batch={batch} key={text(batch,"id")} quarantineOutbox={props.quarantineCleanupOutboxAction} restoreCustomers={props.restoreCleanupCustomersAction} restoreOutbox={props.restoreCleanupOutboxAction}/>)}</>:<p className="empty-state compact">Cleanup controls are unavailable until the protected cleanup history can be verified.</p>}</section><section className="panel"><header className="panel-heading"><div><span className="eyebrow">Provenance</span><h2>Change history</h2></div><span className="status-dot">{props.activity.length}</span></header><div className="data-history">{props.activity.length?props.activity.slice(0,50).map(row=><article key={text(row,"id")}><b>{text(row,"event_type").replace("data_readiness.","").replaceAll("_"," ")}</b><span>{new Date(text(row,"occurred_at")).toLocaleString()}</span><details><summary>Advanced details</summary><small>Event {short(row.event_id)||"—"} · Contact {short(row.contact_id)||"—"}</small></details></article>):<p>No Records &amp; Intake changes have been recorded.</p>}</div></section></div>:null}
  {editor?<div aria-labelledby="record-editor-title" aria-modal="true" className="record-editor-backdrop" role="dialog" onMouseDown={event=>{if(event.target===event.currentTarget)closeEditor();}}><section className="record-editor" ref={editorRef} tabIndex={-1}><header><div><span className="eyebrow">Record details</span><h2 id="record-editor-title">{editor.type==="new"?"Create contact":editor.type==="contact"?(text(editorRow,"display_name")||"Contact"):editor.type==="event"?(text(editorRow,"title")||"Gig"):"Lead"}</h2></div><button aria-label="Close editor" className="icon-button" onClick={closeEditor}>×</button></header>{editor.type==="new"?<ContactEditor action={props.manageContactAction}/>:editor.type==="contact"?<ContactEditor action={props.manageContactAction} row={editorRow}/>:editor.type==="event"?<EventEditor action={props.manageEventAction} row={editorRow??{}} services={props.services}/>:<LeadEditor action={props.manageLeadAction} row={editorRow??{}}/>}<details className="advanced-details"><summary>Advanced details</summary><code>{short(editorRow?.id)||"New record"}</code></details></section></div>:null}</main>
}
