create index if not exists os_activity_events_actor_user_idx on public.os_activity_events(actor_user_id) where actor_user_id is not null;
create index if not exists os_activity_events_contact_idx on public.os_activity_events(contact_id) where contact_id is not null;
create index if not exists os_automation_outbox_event_idx on public.os_automation_outbox(event_id) where event_id is not null;
create index if not exists os_booking_services_quote_item_idx on public.os_booking_services(quote_item_id) where quote_item_id is not null;
create index if not exists os_booking_services_service_idx on public.os_booking_services(service_id) where service_id is not null;
create index if not exists os_bookings_accepted_quote_idx on public.os_bookings(accepted_quote_version_id) where accepted_quote_version_id is not null;
create index if not exists os_builder_submissions_contact_idx on public.os_builder_submissions(contact_id) where contact_id is not null;
create index if not exists os_contact_users_user_idx on public.os_contact_users(user_id);
create index if not exists os_contacts_created_by_idx on public.os_contacts(created_by) where created_by is not null;
create index if not exists os_event_facts_updated_by_idx on public.os_event_facts(updated_by) where updated_by is not null;
create index if not exists os_event_members_contact_idx on public.os_event_members(contact_id) where contact_id is not null;
create index if not exists os_events_builder_submission_idx on public.os_events(builder_submission_id) where builder_submission_id is not null;
create index if not exists os_events_created_by_idx on public.os_events(created_by) where created_by is not null;
create index if not exists os_leads_assigned_to_idx on public.os_leads(assigned_to) where assigned_to is not null;
create index if not exists os_leads_builder_submission_idx on public.os_leads(builder_submission_id) where builder_submission_id is not null;
create index if not exists os_leads_contact_idx on public.os_leads(contact_id);
create index if not exists os_leads_event_idx on public.os_leads(event_id) where event_id is not null;
create index if not exists os_message_threads_created_by_idx on public.os_message_threads(created_by) where created_by is not null;
create index if not exists os_message_threads_event_idx on public.os_message_threads(event_id);
create index if not exists os_messages_sender_contact_idx on public.os_messages(sender_contact_id) where sender_contact_id is not null;
create index if not exists os_messages_sender_user_idx on public.os_messages(sender_user_id) where sender_user_id is not null;
create index if not exists os_planning_answers_updated_by_idx on public.os_planning_answers(updated_by) where updated_by is not null;
create index if not exists os_planning_assignments_template_idx on public.os_planning_assignments(template_id);
create index if not exists os_planning_templates_created_by_idx on public.os_planning_templates(created_by) where created_by is not null;
create index if not exists os_quote_items_service_idx on public.os_quote_items(service_id) where service_id is not null;
create index if not exists os_quote_versions_created_by_idx on public.os_quote_versions(created_by) where created_by is not null;
create index if not exists os_quote_versions_lead_idx on public.os_quote_versions(lead_id) where lead_id is not null;